version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"

    steps:
      - checkout
      - run:
          name: Pre-fetch CocoaPods specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bin/setup
      - run: bin/test
      - run: bin/archive

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
