version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"

    steps:
      - checkout
      - run: bin/setup
      - run: bin/test
      - run: bin/archive

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
